# Generated by Django 4.2.4 on 2025-02-06 20:10

from django.db import migrations, models
import monfintech.models


class Migration(migrations.Migration):

    dependencies = [
        ('monfintech', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default=monfintech.models.generate_unique_transaction_id, max_length=100, unique=True),
        ),
    ]
